// Generated by CIRCT firtool-1.62.1
module FullAdder(	// src/main/scala/comb/Comb.scala:67:7
  input  io_a,	// src/main/scala/comb/Comb.scala:68:14
         io_b,	// src/main/scala/comb/Comb.scala:68:14
         io_cin,	// src/main/scala/comb/Comb.scala:68:14
  output io_sum,	// src/main/scala/comb/Comb.scala:68:14
         io_cout	// src/main/scala/comb/Comb.scala:68:14
);

  assign io_sum = io_a ^ io_b ^ io_cin;	// src/main/scala/comb/Comb.scala:67:7, :76:26
  assign io_cout = io_a & io_b | io_a & io_cin | io_b & io_cin;	// src/main/scala/comb/Comb.scala:67:7, :77:{20,36,46,54}
endmodule

module Adder16(	// src/main/scala/comb/Comb.scala:81:7
  input  [15:0] io_a,	// src/main/scala/comb/Comb.scala:82:14
                io_b,	// src/main/scala/comb/Comb.scala:82:14
  output [15:0] io_sum	// src/main/scala/comb/Comb.scala:82:14
);

  wire _fa_15_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_14_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_14_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_13_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_13_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_12_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_12_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_11_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_11_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_10_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_10_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_9_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_9_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_8_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_8_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_7_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_7_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_6_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_6_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_5_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_5_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_4_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_4_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_3_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_3_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_2_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_2_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_1_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_1_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_io_sum;	// src/main/scala/comb/Comb.scala:97:20
  wire _fa_io_cout;	// src/main/scala/comb/Comb.scala:97:20
  FullAdder fa (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[0]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[0]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (1'h0),	// src/main/scala/comb/Comb.scala:82:14, :97:20
    .io_sum  (_fa_io_sum),
    .io_cout (_fa_io_cout)
  );
  FullAdder fa_1 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[1]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[1]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_1_io_sum),
    .io_cout (_fa_1_io_cout)
  );
  FullAdder fa_2 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[2]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[2]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_1_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_2_io_sum),
    .io_cout (_fa_2_io_cout)
  );
  FullAdder fa_3 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[3]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[3]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_2_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_3_io_sum),
    .io_cout (_fa_3_io_cout)
  );
  FullAdder fa_4 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[4]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[4]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_3_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_4_io_sum),
    .io_cout (_fa_4_io_cout)
  );
  FullAdder fa_5 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[5]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[5]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_4_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_5_io_sum),
    .io_cout (_fa_5_io_cout)
  );
  FullAdder fa_6 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[6]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[6]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_5_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_6_io_sum),
    .io_cout (_fa_6_io_cout)
  );
  FullAdder fa_7 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[7]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[7]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_6_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_7_io_sum),
    .io_cout (_fa_7_io_cout)
  );
  FullAdder fa_8 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[8]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[8]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_7_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_8_io_sum),
    .io_cout (_fa_8_io_cout)
  );
  FullAdder fa_9 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[9]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[9]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_8_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_9_io_sum),
    .io_cout (_fa_9_io_cout)
  );
  FullAdder fa_10 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[10]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[10]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_9_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_10_io_sum),
    .io_cout (_fa_10_io_cout)
  );
  FullAdder fa_11 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[11]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[11]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_10_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_11_io_sum),
    .io_cout (_fa_11_io_cout)
  );
  FullAdder fa_12 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[12]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[12]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_11_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_12_io_sum),
    .io_cout (_fa_12_io_cout)
  );
  FullAdder fa_13 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[13]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[13]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_12_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_13_io_sum),
    .io_cout (_fa_13_io_cout)
  );
  FullAdder fa_14 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[14]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[14]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_13_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_14_io_sum),
    .io_cout (_fa_14_io_cout)
  );
  FullAdder fa_15 (	// src/main/scala/comb/Comb.scala:97:20
    .io_a    (io_a[15]),	// src/main/scala/comb/Comb.scala:98:22
    .io_b    (io_b[15]),	// src/main/scala/comb/Comb.scala:99:22
    .io_cin  (_fa_14_io_cout),	// src/main/scala/comb/Comb.scala:97:20
    .io_sum  (_fa_15_io_sum),
    .io_cout (/* unused */)
  );
  assign io_sum =
    {_fa_15_io_sum,
     _fa_14_io_sum,
     _fa_13_io_sum,
     _fa_12_io_sum,
     _fa_11_io_sum,
     _fa_10_io_sum,
     _fa_9_io_sum,
     _fa_8_io_sum,
     _fa_7_io_sum,
     _fa_6_io_sum,
     _fa_5_io_sum,
     _fa_4_io_sum,
     _fa_3_io_sum,
     _fa_2_io_sum,
     _fa_1_io_sum,
     _fa_io_sum};	// src/main/scala/comb/Comb.scala:81:7, :97:20, :105:19
endmodule

module Comb(	// src/main/scala/comb/Comb.scala:48:7
  input         clock,	// src/main/scala/comb/Comb.scala:48:7
                reset,	// src/main/scala/comb/Comb.scala:48:7
  input  [15:0] io_a,	// src/main/scala/comb/Comb.scala:49:14
                io_b,	// src/main/scala/comb/Comb.scala:49:14
  output [15:0] io_OutSum,	// src/main/scala/comb/Comb.scala:49:14
                io_OutDif	// src/main/scala/comb/Comb.scala:49:14
);

  Adder16 adder (	// src/main/scala/comb/Comb.scala:55:21
    .io_a   (io_a),
    .io_b   (io_b),
    .io_sum (io_OutSum)
  );
  assign io_OutDif = io_a - io_b;	// src/main/scala/comb/Comb.scala:48:7, :62:21
endmodule

